
import { forwardRef, memo, useEffect, useRef, useState, useCallback, useMemo, type ReactNode } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { RotateCcw, Copy, Pencil } from "lucide-react";
import { CodeBlock } from "./CodeBlock";
import { CodeBlockLoader } from "./CodeBlockLoader";
import { ThinkingIndicator } from "./ThinkingIndicator";
import { Button } from "@/components/ui/button";
import { FaUser, FaRobot } from "react-icons/fa";
import { useTheme } from "@/hooks/useTheme";
import { toast } from "sonner";
import { WeatherWidget } from "@/components/WeatherWidget";
import { RSSWidget } from "@/components/RSSWidget";
import { ChatService, ChatMessage } from "@/services/chatService";
import { Storage, STORAGE_KEYS } from "@/utils/storage";
import { saveWelcomeMessage, getCachedWelcomeMessages } from "@/utils/indexedDb";
import { getPrimaryApiKey } from "@/utils/api";

// Rotating fallback welcomes for when dynamic fetch fails
const FALLBACK_WELCOMES: string[] = [
  "Took you long enough. What are we breaking today?",
  "You look bored. Say something worth my time.",
  "I bite. Only if you’re dull. Start talking.",
  "Spill it. I’m not here to babysit your silence.",
  "Your move, darling. Make it interesting.",
  "I sharpen knives on small talk. Try me.",
  "If you hesitate, I’ll start without you.",
  "I’m listening. Barely. Impress me.",
  "Let’s skip the warm-up. What do you want?",
  "Secrets? Problems? Bad ideas? I collect them.",
  "I don’t do coy. Give me the point.",
  "Bold question, reckless plan, or nothing? Choose.",
];

const FALLBACK_WELCOME_INDEX_KEY = 'vivica-fallback-welcome-index';

function getNextFallbackWelcome(): string {
  try {
    const raw = localStorage.getItem(FALLBACK_WELCOME_INDEX_KEY);
    const idx = raw ? Math.max(0, parseInt(raw, 10)) : 0;
    const text = FALLBACK_WELCOMES[idx % FALLBACK_WELCOMES.length];
    localStorage.setItem(
      FALLBACK_WELCOME_INDEX_KEY,
      String((idx + 1) % FALLBACK_WELCOMES.length)
    );
    return text;
  } catch {
    // Fallback to a random choice if storage is unavailable
    return FALLBACK_WELCOMES[Math.floor(Math.random() * FALLBACK_WELCOMES.length)];
  }
}

const getUserName = () => {
  try {
    const profileId = localStorage.getItem(STORAGE_KEYS.CURRENT_PROFILE) || '';
    const profileMem = profileId
      ? JSON.parse(localStorage.getItem(`vivica-memory-profile-${profileId}`) || 'null')
      : null;
    const globalMem = JSON.parse(localStorage.getItem('vivica-memory-global') || 'null');
    const mem = profileMem || globalMem || {};
    return mem.identity?.name || 'User';
  } catch {
    return 'User';
  }
};

interface Message {
  id: string;
  content: string;
  role: 'user' | 'assistant';
  timestamp: Date;
  failed?: boolean;
  isCodeResponse?: boolean;
  codeLoading?: boolean;
  profileId?: string;
}

interface Conversation {
  id: string;
  title: string;
  messages: Message[];
  lastMessage?: string;
  timestamp: Date;
  /** True if the title was generated by Vivica */
  autoTitled?: boolean;
}

interface ProfileBrief {
  isVivica?: boolean;
  model: string;
  fallbackModel?: string;
  systemPrompt: string;
  temperature: number;
}

interface ChatBodyProps {
  conversation: Conversation | null;
  currentProfile?: { id: string } | null;
  isTyping: boolean;
  onRetryMessage?: (messageId: string) => void;
  onRegenerateMessage?: (messageId: string) => void;
  onEditMessage?: (message: Message) => void;
  onSendMessage: (content: string) => void;
  onNewChat: () => void;
  onScroll?: (isAtBottom: boolean) => void;
}

interface MessageRowProps {
  message: Message;
  index: number;
  lastIndex: number;
  isTyping: boolean;
  activeProfileId?: string;
  profileNameById: Record<string, string>;
  userName: string;
  onCopyMessage: (content: string) => void;
  onRetryMessage?: (messageId: string) => void;
  onRegenerateMessage?: (messageId: string) => void;
  onEditMessage?: (message: Message) => void;
}

const MessageRow = memo(({
  message,
  index,
  lastIndex,
  isTyping,
  activeProfileId,
  profileNameById,
  userName,
  onCopyMessage,
  onRetryMessage,
  onRegenerateMessage,
  onEditMessage,
}: MessageRowProps) => {
  const formatTimestamp = (timestamp: Date) => {
    return timestamp.toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit'
    });
  };
  const isLastMessage = index === lastIndex;
  const markdownComponents = useMemo(() => ({
    code({ inline, className, children, ...props }: { inline?: boolean; className?: string; children?: ReactNode }) {
      if (inline) {
        return (
          <code className="inline-code" {...props}>{children}</code>
        );
      }

      const codeText = Array.isArray(children)
        ? children.join('')
        : String(children ?? '');
      const isStreaming = isTyping && isLastMessage;
      const isPartialCode = codeText.trim() === '' || !codeText.trim().endsWith('```');

      if (isStreaming && isPartialCode) {
        return <CodeBlockLoader />;
      }

      return (
        <CodeBlock className={className}>{children}</CodeBlock>
      );
    }
  }), [isTyping, isLastMessage]);

  return (
    <div
      className={`flex flex-col ${
        message.role === 'user' ? 'items-end' : 'items-start'
      } mb-2 ${message.isCodeResponse ? '' : 'slide-up'} group`}
    >
      <div
        className={`flex items-center gap-2 mb-0.5 ${
          message.role === 'user' ? 'flex-row-reverse' : ''
        }`}
      >
        {message.role === 'assistant' ? (
          <>
            <FaRobot className="w-4 h-4" />
            <span className="font-medium text-xs text-muted-foreground">
              {profileNameById[message.profileId || ''] || 'Vivica'}
            </span>
          </>
        ) : (
          <>
            <FaUser className="w-4 h-4" />
            <span className="font-medium text-xs text-muted-foreground">
              {userName}
            </span>
          </>
        )}
      </div>

      <div
        className={`message-bubble ${message.role} ${
          message.isCodeResponse ? 'code-bubble' : ''
        } ${
          message.failed ? 'border-accent/50 bg-accent/10' : ''
        } px-3 py-2 rounded-[2rem] max-w-[95vw] sm:max-w-2xl break-words ${
          message.role === 'user'
            ? 'rounded-br-none ml-6 mr-6'
            : 'rounded-bl-none mr-6 ml-6'
        } ${
          isLastMessage ? 'glow-once' : ''
        }`}
      >
        <div className="prose break-words max-w-none text-sm leading-snug">
          <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
            {
              typeof message.content === 'string'
                ? message.content
                : JSON.stringify(message.content)
            }
          </ReactMarkdown>
          {message.codeLoading && <CodeBlockLoader />}
        </div>

        <div className="flex items-center justify-between mt-2 gap-2">
          <div className={`flex items-center gap-2 text-xs opacity-60 ${
            message.role === 'user' ? 'text-right' : 'text-left'
          }`}>
            {message.isCodeResponse && (
              <span className="inline-block w-2 h-2 rounded-full bg-blue-500/70"
                title="Code response" />
            )}
            {message.failed && (
              <span className="text-red-500/80" title="Failed message">⚠️</span>
            )}
            {formatTimestamp(message.timestamp)}
            {message.profileId !== activeProfileId && (
              <span className="px-1 py-0.5 rounded text-[10px] bg-muted/50">
                {profileNameById[message.profileId || ''] || 'Vivica'}
              </span>
            )}
          </div>

          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button
              variant="ghost"
              size="sm"
              onClick={() =>
                onCopyMessage(
                  typeof message.content === 'string'
                    ? message.content
                    : JSON.stringify(message.content)
                )
              }
              className="h-6 w-6 p-0"
            >
              <Copy className="w-3 h-3" />
            </Button>

            {message.role === 'user' && onEditMessage && (
              (() => {
                const isLastUser = index === lastIndex;
                return isLastUser ? (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => onEditMessage(message)}
                    className="h-6 w-6 p-0"
                  >
                    <Pencil className="w-3 h-3" />
                  </Button>
                ) : null;
              })()
            )}

            {message.role === 'assistant' && onRegenerateMessage && (
              isLastMessage ? (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onRegenerateMessage(message.id)}
                  className="h-6 w-6 p-0"
                >
                  <RotateCcw className="w-3 h-3" />
                </Button>
              ) : null
            )}

            {message.failed && onRetryMessage && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => onRetryMessage(message.id)}
                className="h-6 w-6 p-0 text-accent hover:text-accent/90"
              >
                <RotateCcw className="w-3 h-3" />
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}, (prev, next) =>
  prev.message === next.message &&
  prev.index === next.index &&
  prev.lastIndex === next.lastIndex &&
  prev.isTyping === next.isTyping &&
  prev.activeProfileId === next.activeProfileId &&
  prev.userName === next.userName &&
  prev.profileNameById === next.profileNameById
);

export const ChatBody = forwardRef<HTMLDivElement, ChatBodyProps>(
  ({ conversation, currentProfile, isTyping, onRetryMessage, onRegenerateMessage, onEditMessage, onSendMessage, onNewChat, onScroll }, ref) => {
    const { color, variant } = useTheme();
    const logoSrc = `${import.meta.env.BASE_URL}logo-${color}${variant}.png`;
    const [welcomeMsg, setWelcomeMsg] = useState('');
    const [welcomeError, setWelcomeError] = useState(false);
    const [animateWelcome, setAnimateWelcome] = useState(false);
    const lastWelcomeRef = useRef('');
    const welcomeRequestIdRef = useRef(0);
    const welcomeLoadingRef = useRef(false);
    const shouldAutoScrollRef = useRef(true);
    const scrollRafRef = useRef<number | null>(null);
    const lastMessage = conversation?.messages?.[conversation.messages.length - 1];
    const showThinking = isTyping && !(lastMessage?.isCodeResponse);
    const userName = useMemo(() => getUserName(), []);
    const profileNameById = useMemo(() => {
      try {
        const list: { id: string; name: string }[] = JSON.parse(localStorage.getItem(STORAGE_KEYS.PROFILES) || '[]');
        return list.reduce((acc, item) => {
          acc[item.id] = item.name;
          return acc;
        }, {} as Record<string, string>);
      } catch {
        return {};
      }
    }, []);

    const getScrollContainer = useCallback(() => {
      if (ref && typeof ref !== 'function') {
        return ref.current;
      }
      return null;
    }, [ref]);

    const fetchWelcome = useCallback(async () => {
      if (!conversation || conversation.messages.length) return;
      if (welcomeLoadingRef.current) return;
      const requestId = ++welcomeRequestIdRef.current;
      const canApply = () => welcomeRequestIdRef.current === requestId;
      welcomeLoadingRef.current = true;

      setWelcomeError(false);

      const getFresh = async () => {
        const raw = localStorage.getItem(STORAGE_KEYS.PROFILES) || '[]';
        const profiles = JSON.parse(raw) as ProfileBrief[];
        const vivica = profiles.find(p => p.isVivica) || Storage.createVivicaProfile();

        const apiKey = getPrimaryApiKey();
        if (!apiKey) throw new Error('missing api key');

        const chatService = new ChatService(apiKey);
        const systemPrompt = vivica.systemPrompt;
        const prompt = `${systemPrompt}\n\nVivica, write a short, snarky, surprising welcome message (max 120 characters). Speak in your own voice. Never mention AI or 'assistant.' Only return the message text—no extra formatting, no meta statements, no greetings like 'Welcome.' Do not repeat the previous message.`;

        const reqMessages: ChatMessage[] = [{ role: 'system', content: prompt }];
        const res = await chatService.sendMessage({
          model: vivica.model,
          messages: reqMessages,
          temperature: vivica.temperature,
          max_tokens: 60,
          profile: {
            model: vivica.model,
            codeModel: vivica.model,
            fallbackModel: vivica.fallbackModel,
            temperature: vivica.temperature,
            maxTokens: 60,
          },
        });
        const data = await res.json();
        return data.choices?.[0]?.message?.content?.trim();
      };

      try {
        let text = await getFresh();
        let attempts = 0;
        while (
          text &&
          (text === lastWelcomeRef.current || text.length > 120) &&
          attempts < 2
        ) {
          text = await getFresh();
          attempts++;
        }

        if (text && text.length <= 120) {
          if (!canApply()) return;
          lastWelcomeRef.current = text;
          setWelcomeMsg(text);
          saveWelcomeMessage(text);
          setAnimateWelcome(true);
          return;
        }

        throw new Error('empty');
      } catch {
        try {
          // Graceful fallback: use a cached welcome message if available
          const cached = await getCachedWelcomeMessages();
          const last = cached.sort((a,b) => (b.id! - a.id!))[0];
          if (last?.text) {
            if (!canApply()) return;
            setWelcomeMsg(last.text);
            setWelcomeError(false);
            return;
          }
        } catch {
          // ignore cache errors
        }
        // Use rotating snarky fallback welcomes and allow click-to-retry
        if (!canApply()) return;
        setWelcomeError(true);
        setWelcomeMsg(getNextFallbackWelcome());
      } finally {
        if (canApply()) {
          welcomeLoadingRef.current = false;
        }
      }
    }, [conversation]);

    useEffect(() => {
      const el = getScrollContainer();
      if (!el) return;
      const onScrollInternal = () => {
        const isAtBottom = el.scrollHeight - el.scrollTop <= el.clientHeight + 64;
        shouldAutoScrollRef.current = isAtBottom;
        if (onScroll) onScroll(isAtBottom);
      };
      onScrollInternal();
      el.addEventListener('scroll', onScrollInternal, { passive: true });
      return () => el.removeEventListener('scroll', onScrollInternal);
    }, [getScrollContainer, onScroll]);

    useEffect(() => {
      const el = getScrollContainer();
      if (!el || !shouldAutoScrollRef.current) return;
      if (scrollRafRef.current) {
        cancelAnimationFrame(scrollRafRef.current);
      }
      scrollRafRef.current = requestAnimationFrame(() => {
        el.scrollTop = el.scrollHeight;
      });
      return () => {
        if (scrollRafRef.current) {
          cancelAnimationFrame(scrollRafRef.current);
        }
      };
    }, [conversation?.messages.length, lastMessage?.content, isTyping, getScrollContainer]);

    // Fetch a dynamic welcome message from the LLM whenever the welcome screen is visible
    useEffect(() => {
      if (!conversation || conversation.messages.length) return;

      fetchWelcome();

      const onFocus = () => fetchWelcome();
      const onVisibility = () => {
        if (document.visibilityState === 'visible') fetchWelcome();
      };
      window.addEventListener('focus', onFocus);
      document.addEventListener('visibilitychange', onVisibility);

      return () => {
        welcomeRequestIdRef.current += 1;
        welcomeLoadingRef.current = false;
        window.removeEventListener('focus', onFocus);
        document.removeEventListener('visibilitychange', onVisibility);
      };
    }, [conversation, fetchWelcome]);

    useEffect(() => {
      if (!welcomeMsg) return;
      setAnimateWelcome(true);
      const t = setTimeout(() => setAnimateWelcome(false), 400);
      return () => clearTimeout(t);
    }, [welcomeMsg]);

    const handleCopyMessage = useCallback((content: string) => {
      navigator.clipboard.writeText(content);
      toast.success("Message copied to clipboard");
    }, []);


    return (
      <div
        ref={ref}
        className="flex-1 overflow-y-auto p-4 space-y-6 relative"
      >
        {!conversation?.messages.length ? (
          // Empty state
          <div className="flex flex-col items-center justify-center h-full text-center space-y-8 max-w-2xl mx-auto -mt-8">
            <div className="space-y-4">
              <img src={logoSrc} alt="Vivica" className="w-40 h-40 mx-auto" />
              <h2 className="text-3xl font-bold">Welcome to Vivica</h2>
              <p
                onClick={() => welcomeError && fetchWelcome()}
                className={`text-lg text-muted-foreground ${animateWelcome ? 'fade-in slide-up' : ''} ${welcomeError ? 'cursor-pointer' : ''}`}
              >
                {welcomeMsg}
              </p>
            </div>

            <div className="grid grid-cols-1 gap-4 w-full max-w-md">
              <WeatherWidget />
              <RSSWidget onSendMessage={onSendMessage} onNewChat={onNewChat} />
            </div>
          </div>
        ) : (
          // Messages
          <div className="space-y-4 sm:space-y-6 max-w-full sm:max-w-4xl mx-auto overflow-x-hidden">
            {conversation.messages.map((message, index) => (
              <MessageRow
                key={message.id}
                message={message}
                index={index}
                lastIndex={conversation.messages.length - 1}
                isTyping={isTyping}
                activeProfileId={currentProfile?.id}
                profileNameById={profileNameById}
                userName={userName}
                onCopyMessage={handleCopyMessage}
                onRetryMessage={onRetryMessage}
                onRegenerateMessage={onRegenerateMessage}
                onEditMessage={onEditMessage}
              />
            ))}
            {showThinking && (
              <div className="px-6 pt-2">
                <ThinkingIndicator />
              </div>
            )}
          </div>
        )}
      </div>
    );
  }
);

ChatBody.displayName = "ChatBody";
